# Generated by Django 4.0.1 on 2022-03-01 17:09


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_eemial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eemial',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='sno',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='todo',
        ),
    ]
